mule-module-apikit/src/main/resources/console2/scripts/api-console.js
console commit: 8768a01e5f4046f8c697a456d601cb9210408682
=> APIKIT-543: Changing API Console to v 3.0.4. 

mule-module-apikit/src/main/java/org/mule/module/apikit/CharsetUtils.java, mule-module-apikit/src/main/java/org/mule/module/apikit/validation/RestJsonSchemaValidator.java, mule-module-apikit/src/main/java/org/mule/module/apikit/validation/RestXmlSchemaValidator.java, mule-module-apikit/src/test/java/org/mule/module/apikit/leagues/LeaguesTestCase.java, mule-module-apikit/src/test/java/org/mule/module/apikit/schema/EncodingTestCase.java, mule-module-apikit/src/test/resources/org/mule/module/apikit/schema/encoding-config.xml
(cherry picked from commit 3a33ff1d0fc8f52b70b6850342715801f18b97dc)
=> APIKIT-542: fix payload encoding detection (for 1.7.x)

apikit-tools/apikit-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, apikit-tools/apikit-archetype/src/main/resources/archetype-resources/src/main/mule/mule-config.xml
- Removing compatibility mode
- Adding interpretRequestErrors property to the generated listener
- Removing error-response generation within listener
=> APIKIT-774: Update archetype

apikit-tools/apikit-maven-plugin/pom.xml, apikit-tools/apikit-scaffolder/pom.xml, apikit-tools/apikit-scaffolder/src/main/java/org/mule/tools/apikit/output/scopes/APIKitFlowScope.java, apikit-tools/apikit-scaffolder/src/test/java/org/mule/tools/apikit/ScaffolderMule4Test.java, apikit-tools/apikit-scaffolder/src/test/java/org/mule/tools/apikit/output/MuleConfigGeneratorTest.java, apikit-tools/apikit-scaffolder/src/test/java/org/mule/tools/apikit/output/scopes/APIKitFlowScopeTest.java
- Updating maven-plugin-plugin version from 3.2 to 3.4
- Adding Dataweave dependency
=> APIKIT-776: Scaffolder - Transform generation should use dw language

parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v08/model/ActionImpl.java, parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v08/model/ResourceImpl.java, parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v08/model/ResponseImpl.java, parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v10/model/ActionImpl.java, parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v10/model/ResourceImpl.java, parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v10/model/ResponseImpl.java
WITHOUT FIX: 
Requests per second:    171.89 [#/sec] (mean)
WITH FIX
Requests per second:    3107.87 [#/sec] (mean)
=> APIKIT-854: Performance issue accessing V2 parser

mule-module-apikit/src/main/java/org/mule/module/apikit/validation/RestJsonSchemaValidator.java, mule-module-apikit/src/test/java/org/mule/module/apikit/RequestSchemaValidationTestCase.java
Maybe would be good to limit the quantity of message showed instead of showing all.
=> APIKIT-836: Return all errors in json schema validation.

mule-apikit-module/src/main/java/org/mule/module/apikit/validation/body/schema/v1/RestJsonSchemaValidator.java, mule-apikit-module/src/test/java/org/mule/module/apikit/validation/body/schema/RestJsonSchemaValidatorTestCase.java
Added feature in APIkit-4.x (https://www.mulesoft.org/jira/browse/APIKIT-836)
=> apikit-836

mule-apikit-module/pom.xml, mule-apikit-tools/mule-apikit-archetype/src/main/resources/archetype-resources/pom.xml
=> Revert "APIKIT-983: mule.http.connector.version version changed"

mule-apikit-module/src/main/java/org/mule/module/apikit/Configuration.java, mule-apikit-module/src/main/java/org/mule/module/apikit/Router.java
Also, refactor router to not depend on MessageProcessors
=> MULE-12716: Remove registries from API

mule-apikit-metadata/src/main/java/org/mule/module/apikit/metadata/ApikitElementIdentifiers.java, mule-apikit-metadata/src/main/java/org/mule/module/apikit/metadata/ApplicationModelWrapper.java, mule-apikit-metadata/src/main/java/org/mule/module/apikit/metadata/Metadata.java, mule-apikit-metadata/src/test/java/org/mule/module/apikit/metadata/MetadataModuleTestCase.java, mule-apikit-metadata/src/test/java/org/mule/module/apikit/metadata/MetadataTestCase.java, mule-apikit-metadata/src/test/java/org/mule/module/apikit/metadata/utils/ApplicationModelWrapper.java, mule-apikit-metadata/src/test/java/org/mule/module/apikit/metadata/utils/MockedApplicationModel.java
=> MULE-13592: Remove mention to spring on api packages for

mule-apikit-module/src/main/java/org/mule/module/apikit/Router.java
This requires https://github.com/mulesoft/mule/pull/5886
=> MULE-10519: Move all exception classes away from MessagingException

pom.xml
New parser release. Changing to 1.0.18-SNAPSHOT
=> New parser release. Changing to 1.0.18-SNAPSHOT

parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/ParserV2Utils.java, parser-wrapper/interface-impl-v2/src/test/java/org/mule/raml/implv2/v10/InterfaceV10TestCase.java, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/library-references-absolute/input.raml, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/library-references-absolute/libraries/resourceTypeLibrary.raml, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/library-references-absolute/libraries/traitsLibrary.raml, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/library-references-absolute/libraries/typeLibrary.raml, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/library-references-absolute/model.json, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/library-references-absolute/traits/trait.raml
…n using absolute includes from files in subfolders
=> APIKIT-1833: IRaml#getAllReferences method returns an invalid URI when using absolute includes from files in subfolders

mule-apikit-tools/mule-apikit-scaffolder/src/main/java/org/mule/tools/apikit/misc/ExampleUtils.java
When the VM's encoding and the files encoding are different, there are cases in which the encoded strings that comes from the parser has strange characters (see SE-10803 for an example). In the case of DataWeave examples we know they will be JSON or XML files, and UTF-8 is the encouraged encoding for both of these formats.
What this change does is check for the default encoding of the VM, and if it's not UTF-8, the string is decoded using the decoder for the default charset, it is re-encoded correctly in UTF-8.
DataWeaveResult's getContentAsString() has the same problem, it also uses the default encoding to read the InputStream, and it's not desirable in these cases. So, instead, the InputStream is retrieved and read in UTF-8.
=> SE-10803 Adding encoding correction on ExampleUtils

apikit-tools/apikit-scaffolder/src/main/java/org/mule/tools/apikit/input/MuleConfigParser.java, apikit-tools/apikit-scaffolder/src/main/java/org/mule/tools/apikit/input/RAMLFilesParser.java, apikit-tools/apikit-scaffolder/src/test/java/org/mule/tools/apikit/input/MuleConfigParserTest.java, apikit-tools/apikit-scaffolder/src/test/resources/separate-config/global.xml, apikit-tools/apikit-scaffolder/src/test/resources/separate-config/simple.raml, apikit-tools/apikit-scaffolder/src/test/resources/separate-config/simple.xml
=> APIKIT-1886: Fix order issue when the configs are at different files

mule-module-apikit/pom.xml
…SettableFuture when running munit from commandline
=> APIKIT-1910: NoClassDefFoundError: com/google/common/util/concurrent/SettableFuture when running munit from commandline

mule-module-apikit/src/main/java/org/mule/module/apikit/HttpRestProxyRequest.java, mule-module-apikit/src/main/java/org/mule/module/apikit/HttpRestRequest.java, mule-module-apikit/src/main/java/org/mule/module/apikit/OutputRepresentationHandler.java, mule-module-apikit/src/test/java/org/mule/module/apikit/output/OutputRepresentationHandlerTestCase.java
=> APIKIT-1995: Content-type response header case causes validation errors on RAML fix ProxyTestCase

parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v10/model/RamlImpl10V2.java, parser-wrapper/interface-impl-v2/src/test/java/org/mule/raml/implv2/v10/InterfaceV10TestCase.java, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/get-all-refs/array-example.raml, parser-wrapper/interface-impl-v2/src/test/resources/org/mule/raml/implv2/v10/get-all-refs/examples/getAllOrderResponse.raml
…nabled: NumberFormatException: For input string: mediaType
=> APIKIT-1975: Issue while deploying applications with APIKit Console enabled: NumberFormatException: For input string: mediaType

mule-module-apikit/src/main/java/org/mule/module/apikit/AbstractConfiguration.java, parser-wrapper/interface-impl-v2/src/main/java/org/mule/raml/implv2/v10/model/ParameterImpl.java
=> APIKIT-2034: API Kit is failing to validate yyyy-m-d and yyyy-m-dThh:mi:ss formats

apikit-examples/leagues/pom.xml, apikit-examples/pom.xml, apikit-examples/studio-example/pom.xml, apikit-spi/pom.xml, apikit-tools/apikit-archetype/pom.xml, apikit-tools/apikit-maven-plugin/pom.xml, apikit-tools/apikit-scaffolder/pom.xml, apikit-tools/pom.xml, distribution/pom.xml, mule-module-apikit/pom.xml, parser-wrapper/interface-impl-v1/pom.xml, parser-wrapper/interface-impl-v2/pom.xml, parser-wrapper/parser-interface/pom.xml, parser-wrapper/pom.xml, pom.xml
This reverts commit a291ad9a49af6a9e5fcb8f4115b42151414ae051.
=> Revert "Revert "Update version to 3.9.5-SNAPSHOT in folder: pom.xml""

pom.xml
This reverts commit ca7346f05a9532f96a6d4d5f6b5f8d9c8ef3c3ce.
=> Revert "APIKIT-2817: Bump up parser versions (#574)"

pom.xml
This reverts commit ca7346f05a9532f96a6d4d5f6b5f8d9c8ef3c3ce.
=> Revert "APIKIT-2817: Bump up parser versions (#574)" (#580)

apikit-examples/leagues/pom.xml, apikit-examples/pom.xml, apikit-examples/studio-example/pom.xml, apikit-spi/pom.xml, apikit-tools/apikit-archetype/pom.xml, apikit-tools/apikit-maven-plugin/pom.xml, apikit-tools/apikit-scaffolder/pom.xml, apikit-tools/pom.xml, distribution/pom.xml, mule-module-apikit/pom.xml, parser-wrapper/interface-impl-v1/pom.xml, parser-wrapper/interface-impl-v2/pom.xml, parser-wrapper/parser-interface/pom.xml, parser-wrapper/pom.xml, pom.xml
We need to release version 3.9.5-20220920, and for that we need the proper value ion the POM files on api kit.
Affect W-11780835
=> W-11780835 Modifying POM versions to support version 3.9.5-20220920.

apikit-examples/leagues/pom.xml, apikit-examples/pom.xml, apikit-examples/studio-example/pom.xml, apikit-spi/pom.xml, apikit-tools/apikit-archetype/pom.xml, apikit-tools/apikit-maven-plugin/pom.xml, apikit-tools/apikit-scaffolder/pom.xml, apikit-tools/pom.xml, distribution/pom.xml, mule-module-apikit/pom.xml, parser-wrapper/interface-impl-v1/pom.xml, parser-wrapper/interface-impl-v2/pom.xml, parser-wrapper/parser-interface/pom.xml, parser-wrapper/pom.xml, pom.xml
W-12363278 change versions to 3.9.5-20230217
=> W-12363278 change versions to 3.9.5-20230217

apikit-examples/leagues/pom.xml, apikit-examples/pom.xml, apikit-examples/studio-example/pom.xml, apikit-spi/pom.xml, apikit-tools/apikit-archetype/pom.xml, apikit-tools/apikit-maven-plugin/pom.xml, apikit-tools/apikit-scaffolder/pom.xml, apikit-tools/pom.xml, distribution/pom.xml, mule-module-apikit/pom.xml, parser-wrapper/interface-impl-v1/pom.xml, parser-wrapper/interface-impl-v2/pom.xml, parser-wrapper/parser-interface/pom.xml, parser-wrapper/pom.xml, pom.xml
W-13829682 release apikit version
=> W-13829682 release apikit version

pom.xml
=> W-13829682 Update pom.xml

apikit-examples/leagues/pom.xml, apikit-examples/pom.xml, apikit-examples/studio-example/pom.xml, apikit-spi/pom.xml, apikit-tools/apikit-archetype/pom.xml, apikit-tools/apikit-maven-plugin/pom.xml, apikit-tools/apikit-scaffolder/pom.xml, apikit-tools/pom.xml, distribution/pom.xml, mule-module-apikit/pom.xml, parser-wrapper/interface-impl-v1/pom.xml, parser-wrapper/interface-impl-v2/pom.xml, parser-wrapper/parser-interface/pom.xml, parser-wrapper/pom.xml, pom.xml
W-13840063 revert versions snapshot
=> W-13840063 revert versions snapshot
